# Generated by Django 5.2 on 2025-05-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="coffee_type",
            field=models.CharField(
                choices=[
                    ("Arabica", "Arabica"),
                    ("Robusta", "Robusta"),
                    ("Liberica", "Liberica"),
                    ("Excelsa", "Excelsa"),
                ],
                default="Arabica",
                max_length=20,
            ),
        ),
    ]
